### PR TITLE
Parallel collectors

### LINKED ISSUE #22: use multiple collectors to reduce /metrics latency
The prometheus /gatherer spins off a goroutine for every Collector to collect metrics in parallel (https://github.com/prometheus/client_golang/blob/master/prometheus/registry.go#L440)

The harbor exporter is registered as a single collector that grabs all the metrics serially (https://github.com/c4po/harbor_exporter/blob/master/harbor_exporter.go#L310)

In my deployment scraping /metrics regularly takes 20-30 seconds, exceeding the default interval and scrape timeouts of 10 seconds.

### PR DESCRIPTION
**Pull request by cjnosal**
Use collectors so the Prometheus SDK can collect metrics from different categories in parallel
Add goroutines to replication/repo collectors to improve latency for Harbors with large amounts of projects
Add an `up` and `latency` metric for each collector
Fixes #22

### CODE REVIEW

**Comment by c4po** [comment]
@xtreme-conor-nosal are the changes all done/pushed or you still working on something.

**Comment by cjnosal** [comment]
I'm done for now

**Comment by cjnosal** [comment]
@c4po it looks like the circleci task is stuck?

**Comment by c4po** [comment]
@xtreme-conor-nosal  sorry I was busy on something else.
I reviewed your changes, cannot understand some of them. Can you spit this PR into 2 or 3 PRs which only fix one issue each?

**Comment by cjnosal** [comment]
Sure, I should have kept the refactoring PR separate from the features added on top. Looks like everything needs re-basing anyway. In the meantime a quick overview (tried to keep the commits scoped):

Refactoring for performance:
- defining Prometheus Collectors for each harbor API allows the Prometheus SDK to call each collector in a separate go routine (latency of a /metrics call bounded by the slowest collector)
- adding goroutines to collectors use parallelism to process potentially large data sets (e.g. list of repos)
- some of the complexity (shared up channel) is to preserve the exiting 'up' metric when it's now based on several asynchronous operations

Features:
- adding individual 'up' metrics for each collector to add more nuance to the binary 'up' indicator (i.e. when 'up' is 0 did one API call fail or several)
- adding latency measures for each collector both as a harbor measure, and a means to validate the refactoring and the impact of changing the number of threads in the pools

**Comment by cjnosal** [comment]
Closing - will start a set of smaller PRs

**Pull request closed without merging**
