### PR TITLE
Do not access `err` when it might be `nil`

### LINKED ISSUE #1: Docker container crashed
Hi,

I tried to run the service as docker but it's throwing below error message and docker dead while hit ipaddress:9107

`level=info ts=2020-02-13T08:35:01.260Z caller=harbor_exporter.go:261 msg="Starting harbor_exporter" version="(version=v0.2, branch=master,` `revision=70e0d756ff79908745b4395439df31cb57c1f7eb)"`
`level=info ts=2020-02-13T08:35:01.260Z caller=harbor_exporter.go:262` `build_context="(go=go1.13.7, user=root, date=2020-02-13-07:48:34-UTC)"`
`level=info ts=2020-02-13T08:35:01.327Z caller=harbor_exporter.go:304 msg="Listening on` `address" address=:9107`

`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x877144]`
`goroutine 39 [running]:`
`main.HarborClient.request(0xc00018c570, 0x7ffe685d2f21, 0x1c, 0xc000022030, 0xe, 0xc000022050,` `0xa, 0x1dcd6500, 0x0, 0xa48680, ...)`
        `/src/harbor_exporter.go:146 +0x3a4`
`main.(*Exporter).collectScanMetric(0xc0000a18c0, 0xc000104060, 0xc0003aaea8)`
        `/src/metrics_scan.go:19 +0xac`
`main.(*Exporter).Collect(0xc0000a18c0, 0xc000104060)`
        `/src/harbor_exporter.go:221 +0x3c`
`github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()`
        `/go/pkg/mod/github.com/prometheus/client_golang@v1.4.0/prometheus/registry.go:443 +0x19d`
`created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather`
        `/go/pkg/mod/github.com/prometheus/client_golang@v1.4.0/prometheus/registry.go:454 +0x57d`

### PR DESCRIPTION
**Pull request by cmur2**
Fixes #1

### CODE REVIEW

**Comment by cmur2** [comment]
@c4po I tested this by building the Docker image and using it against the Harbor instance that does not have container scanner setup and now I get all available metrics without crash.

**Review by c4po — APPROVED** [review]
thanks for the fix

**Comment by cmur2** [comment]
@c4po can you maybe release a new version of the Docker image based on `master` to include the fix please?

**Comment by c4po** [comment]
@cmur2 tag `latest` is auto build on `master` branch and tag `v0.3` is just created.

**Pull request merged**
