### PR TITLE
Helm chart 

### LINKED ISSUE #37: Build Helm Chart for harbor-exporter
* build a helm chart
* create the installation document

* (bonus point), add to https://github.com/goharbor/harbor-helm

### PR DESCRIPTION
**Pull request by bainss**
Helm chart for deploying harbor_exporter

### CODE REVIEW

**Comment by c4po** [comment]
@bainss , thank you for this. can you add the usage to readme or create a new document for it?

**Comment by c4po** [comment]
please also remove the duplicated file in the PR. e.g. Chart.yaml vs chart/Chart.yaml

**Comment by c4po** [comment]
are templates/ folder and  charts/templates/ folder duplicated?

**Comment by bainss** [comment]
Added updates to the READme and removed the duplicates

**Comment by bainss** [comment]
Hi @c4po  can you review this and the other PR please

**Pull request closed without merging**
