### PR TITLE
Iterate over pages of results

### LINKED ISSUE #29: only first page of harbor results are fetched
Harbor APIs are paginated. If the number of projects/repos/etc exceeds the default page size then not all metrics will be exported.

A quick fix might by to set an excessively large default page size (or expose as an environment variable) but that might have performance impacts. A more rigorous solution will need to loop over each page of results.

### PR DESCRIPTION
**Pull request by cjnosal**
Fix #29

### CODE REVIEW

**Comment by badsmoke** [comment]
solves the 10 entries problem

**Review by badsmoke — APPROVED** [review]

**Comment by c4po** [comment]
are these the only apis that support pagination?

**Comment by cjnosal** [comment]
The other APIs the exporter currently calls don't return lists. All list APIs support pagination.
________________________________

**Comment by c4po** [comment]
I would like to implement this with `x-total-count`  in the response header.

**Comment by cjnosal** [comment]
Interesting, I wasn't aware of the header. That could save an unneeded API call (compared to my current implementation) whenever the dataset is an exact multiple of page size (though if default page size is harbor's max of 500 that may not be too frequent).

This PR could be adapted after rebasing (unless you have a separate effort in flight). Using the header would require `request` to return the response headers (or at least the count if present). Then the checks for `len(data) == pageSize` would become something like `(page - 1) * pageSize + len(data) < x-total-count`

**Pull request closed without merging**
