### PR TITLE
add clair vulnerability scan metrics

### PR DESCRIPTION
**Pull request by IduVlad**

### CODE REVIEW

**Comment by lukasmrtvy** [comment]
any chance to integrate also trivy scanner ? ( related https://github.com/kaidotdev/kube-trivy-exporter )

**Comment by c4po** [comment]
@IduVlad do you have time to rebase your changes?

**Comment by dkulchinsky** [comment]
@IduVlad we would be very interested in this enhancement 👍 one question though related to @lukasmrtvy's comment, reading through the code I believe the vulnerability report used here is not Clair specific, instead it should return the latest security summary of the artifact based on whatever scan data that is currently available, regardless of which scanner was used, isn't it?

**Comment by IduVlad** [comment]
@dkulchinsky you're right. I will try to find some time next week to finish this feature.

**Comment by IduVlad** [comment]
moved to #60

**Pull request closed without merging**
